### model
model_name_or_path: ./model/Qwen2.5/Qwen2.5-14B-Instruct

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: ./examples/deepspeed/ds_z3_offload_config.json
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

dataset: dpo_o1_4o_train,dpo_qwen_o1_train,dpo_qwen_4o_train
template: qwen
cutoff_len: 8192
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ./kg-o1/qwen_14b_dpo
logging_steps: 3
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-5 
num_train_epochs: 5
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
eval_dataset: dpo_o1_4o_dev
per_device_eval_batch_size: 1
eval_strategy: epoch


